### DISCUSSION TITLE
Make playground activation optional on the API

### DISCUSSION THREAD

**Discussion by matteovivona** [sorry-cypress/sorry-cypress#622] [Ideas]
I don't see it as wise to enable Apollo Server's playground by default. Using `ApolloServerPluginLandingPageDisabled` we could parameterize the activation of the landing page.

I did a quick test on my fork.

```
const apolloServer = new ApolloServer({
    typeDefs,
    resolvers,
    dataSources: () => dataSources,
    introspection: true,
    plugins: [
      APOLLO_PLAYGROUND === 'false'
        ? ApolloServerPluginLandingPageDisabled()
        : ApolloServerPluginLandingPageGraphQLPlayground(),
    ],
  });
```

With APOLLO_PLAYGROUND set on `false`
```
api:
    build:
      dockerfile: packages/api/Dockerfile
      context: .
    image: agoldis/sorry-cypress-api:${VERSION:-latest}
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      APOLLO_PLAYGROUND: 'false'
    ports:
      - 4000:4000
    depends_on:
      - mongo
```
![Screenshot 2022-08-13 at 10 55 11](https://user-images.githubusercontent.com/6388707/184476697-91c649cd-2703-439e-88a1-781223b08920.png)

With APOLLO_PLAYGROUND set on `true`
```
api:
    build:
      dockerfile: packages/api/Dockerfile
      context: .
    image: agoldis/sorry-cypress-api:${VERSION:-latest}
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      APOLLO_PLAYGROUND: 'true'
    ports:
      - 4000:4000
    depends_on:
      - mongo
```
![Screenshot 2022-08-13 at 10 56 18](https://user-images.githubusercontent.com/6388707/184476709-f2ed4599-ecd2-4701-b555-0ce7caaefbf7.png)

I can create a PR asap
