### DISCUSSION TITLE
Disable the liveness probe logs

### DISCUSSION THREAD

**Discussion by matteovivona** [sorry-cypress/sorry-cypress#623] [Ideas]
To avoid flooding centralized logs collection systems, it would be interesting to disable, via pino native option `autoLogging.ignore`, all the logs from the path `/health-check-db' and '/ping`.

```
app
  .use(
    PROBE_LOGGER === 'true'
      ? expressPino({
          logger: getLogger(),
        })
      : expressPino({
          logger: getLogger(),
          autoLogging: {
            ignorePaths: ['/health-check-db', '/ping'],
          },
        })
  )
  .use(
    express.json({
      limit: '50mb',
    })
  )
  .use(setLoggerMiddleware);
```

I did a quick test on my fork.

With PROBE_LOGGER set on `false`
```
director:
    build:
      dockerfile: packages/director/Dockerfile
      context: .

    image: agoldis/sorry-cypress-director:${VERSION:-latest}
    environment:
      DASHBOARD_URL: http://localhost:8080
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      EXECUTION_DRIVER: '../execution/mongo/driver'
      SCREENSHOTS_DRIVER: '../screenshots/s3.driver'
      AWS_ACCESS_KEY_ID: 'key'
      AWS_SECRET_ACCESS_KEY: 'secret'
      S3_BUCKET: sorry-cypress
      PROBE_LOGGER: "false"
    ports:
      - 1234:1234
    depends_on:
      - mongo

```
![Screenshot 2022-08-13 at 12 03 50](https://user-images.githubusercontent.com/6388707/184479016-85af5320-10c8-4eb5-a3f2-ce73abc376fe.png)

With PROBE_LOGGER set on `true`
```
director:
    build:
      dockerfile: packages/director/Dockerfile
      context: .

    image: agoldis/sorry-cypress-director:${VERSION:-latest}
    environment:
      DASHBOARD_URL: http://localhost:8080
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      EXECUTION_DRIVER: '../execution/mongo/driver'
      SCREENSHOTS_DRIVER: '../screenshots/s3.driver'
      AWS_ACCESS_KEY_ID: 'key'
      AWS_SECRET_ACCESS_KEY: 'secret'
      S3_BUCKET: sorry-cypress
      PROBE_LOGGER: "true"
    ports:
      - 1234:1234
    depends_on:
      - mongo
```
![Screenshot 2022-08-13 at 12 04 22](https://user-images.githubusercontent.com/6388707/184479011-a59500cc-f519-4df2-801a-28e6b2fcc218.png)

I can create a PR asap
