### DISCUSSION TITLE
Sorry Cypress Director Pods dies

### DISCUSSION THREAD

**Discussion by Lory1990** [sorry-cypress/sorry-cypress#676] [Q&A] [answered]
Hi! I am running sorry Cypress with Gitlab Pipielines, here is the pipeline:

```
download-libraries:
  image: cypress/browsers:node18.6.0-chrome105-ff104
  timeout: 180m
  allow_failure: false
  cache:
    paths:
      - node_modules/
      - .npm
      - .cache/Cypress
      - cache/Cypress
  script:
    - npm install
    - npx cypress cache path
    - npx cypress cache list
    - npx cypress verify
    - npx cypress info
  artifacts:
    paths:
      - .npm
      - .cache/Cypress
      - cache/Cypress
      - node_modules

test-on-sorry-cypress:
  image: cypress/browsers:node18.6.0-chrome105-ff104
  timeout: 180m
  when: on_success
  parallel: 5
  allow_failure: true
  needs:
    - download-libraries
  tags:
    - cypress-runner
  variables:
    FF_USE_FASTZIP: "true"
  script:
    - npx cy2 run --record --key ${CYPRESS_RECORD_KEY} --browser chrome --ci-build-id ${CI_PIPELINE_IID} --group ${CYPRESS_RECORD_KEY} --parallel
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
```

The runners with tag `cypress-runner` are pods deployed in Azure Kubernetes Services and seems that some of them "dies" before starting the run with this message:

```
$ npx cy2 run --record --key ${CYPRESS_RECORD_KEY} --browser chrome --ci-build-id ${CI_PIPELINE_IID} --group ${CYPRESS_RECORD_KEY} --parallel
[cy2] Running cypress with API URL: https://cypress-api.step4business.com/
[54:1103/050854.505865:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 230: Permission denied (13)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[230:1103/050855.911187:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Couldn't find tsconfig.json. tsconfig-paths will be skipped

====================================================================================================
  (Run Starting)
[.....]
====================================================================================================

ERROR: Job failed: pod "runner-rxduhhn-project-28738-concurrent-0x9b94" status is "Failed"
```

and this is totally random... do you have the same issue?
