### ISSUE TITLE
Successfully saved ( and uploaded ) screenshots are not shown in dashboard. Videos are.

### ISSUE THREAD

**Issue by webdevotion** [sorry-cypress/sorry-cypress#154]
### Context

Using the latest docker images ( `docker-compose.minio.yml` ). 

```bash
❯ docker images | grep sorry
agoldis/sorry-cypress-dashboard                                            latest                      43bda194ee83        4 days ago          1.28GB
agoldis/sorry-cypress-api                                                  latest                      115e25a049a5        4 days ago          340MB
agoldis/sorry-cypress-director                                             latest                      76d51f3ffed2        4 days ago          318MB
```

### Cypress Output

```text
...
(Uploading Results)

  - Done Uploading (1/3) /....ui.testing/cypress/screenshots/startpage.spec.js/Startpage Guest User -- check if main title exists.png
  - Done Uploading (2/3) /.....ui.testing/cypress/screenshots/startpage.spec.js/Startpage Guest User -- has a flyout menu with many links to apps (failed).png
  - Done Uploading (3/3) /.....ui.testing/cypress/videos/startpage.spec.js.mp4
...
```

### What actually happens
Videos are shown on the spec result page, but there is no sign of screenshots. The screenshots do get saved locally, cypress logs clearly state that the resulting files have been uploaded and the files are visible in my local Minio instance ( `docker-compose.minio.yml` ). There are no log entries in the browser console.

<img width="1463" alt="Screenshot 2020-10-06 at 11 27 22" src="https://user-images.githubusercontent.com/50583/95183967-ff1de380-07c6-11eb-8bf7-6436741c852c.png">

### Expected
Screenshots are visible and accessible by using the dashboard UI.

**Comment by webdevotion** [comment]
The React state of the component seems to be fine. The `testId` of `test` and `screenshots[0]` are equal ( `r8` ).

<img width="636" alt="Screenshot 2020-10-06 at 11 54 08" src="https://user-images.githubusercontent.com/50583/95194259-588d0f00-07d5-11eb-856d-9757876ed309.png">

Just pulled the latest docker images and am seeing the same issue.
```text
❯ docker images | grep sorry
agoldis/sorry-cypress-dashboard                                            latest                      dd5a58ac83b4        40 hours ago        1.28GB
agoldis/sorry-cypress-api                                                  latest                      afbb1b519b31        40 hours ago        340MB
agoldis/sorry-cypress-director                                             latest                      d00ef9a8a498        40 hours ago        318MB
```

**Comment by gespispace** [comment]
Hello, you need change config `docker-compose.minio.yml` on
Where `youIP` is external ip your virtual machine.
```yml
version: '3.6'

services:
  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017

  storage:
    image: minio/minio
    hostname: 'storage'
    environment:
      MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
      MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
    volumes:
      - ./data/data-minio-cypress:/data
    command: server /data
    ports:
      - 9000:9000

  createbuckets:
    image: minio/mc
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc config host add myminio http://storage:9000 MW32h3gd6HvjBEgTRx t6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7;
      /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress;
      /usr/bin/mc mb myminio/sorry-cypress;
      /usr/bin/mc policy set download myminio/sorry-cypress;
      /usr/bin/mc policy set public myminio/sorry-cypress;
      exit 0;
      "
  director:
    image: agoldis/sorry-cypress-director:latest
    links:
      - 'storage:storage'
    environment:
      DASHBOARD_URL: http://<youIP>:8080
      EXECUTION_DRIVER: '../execution/mongo/driver'
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'

      SCREENSHOTS_DRIVER: '../screenshots/minio.driver'
      MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
      MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
      MINIO_ENDPOINT: 'http://<youIP>'
      MINIO_URL: 'http://<youIP>'
      MINIO_PORT: '9000'
      MINIO_USESSL: 'false'
      MINIO_BUCKET: sorry-cypress
    ports:
      - 1234:1234
    depends_on:
      - mongo
      - storage
  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
    ports:
      - 4000:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://<youIP>:4000
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - api
```
