### ISSUE TITLE
[Question] Your Record Key is not valid with this project

### ISSUE THREAD

**Issue by guidiego** [sorry-cypress/sorry-cypress#239]
## Summary
When I try to exec my code I have problems in run this key fixedstring.fixedstring.fixedstring.GITHUB_SHA.

`Your Record Key project...acb72 is not valid with this project: glados`

## How to reproduce
I only execute the same code from Sorry Cypress example with the key in previous format

## Environment

- sorry-cypress version: latest
- cypress version: latest
- platform: AWS
- service: director

**Comment by agoldis** [comment]
Are you sure you're not using the original cypress dashboard? sorry-cypress doesn't check record keys

**Comment by guidiego** [comment]
Yeah @agoldis actually I run local and sometimes they pass, sometimes they give an error. I see that usually works when I add something with `-`.

**Comment by guidiego** [comment]
```
default:
  cdn_url: "https://cdn.cypress.io"
  desktop_url: "https://download.cypress.io/desktop"
  desktop_manifest_url: https://download.cypress.io/desktop.json
  chromium_url: https://download.cypress.io/chromium
  chromium_manifest_url: https://download.cypress.io/chromium.json

development: &development
  api_url: "http://xxxxxx:8080/"
  on_url: "http://localhost:8080/"

test:
  <<: *development

staging:
  api_url: "http://xxxxxx:8080/"
  on_url: "https://on.cypress.io/"

production:
  api_url: "http://xxxxxx:8080/"
  on_url: "https://on.cypress.io/"
```
