### ISSUE TITLE
Dashboard unable to load video and images

### ISSUE THREAD

**Issue by amalhotragannett** [sorry-cypress/sorry-cypress#352]
## Steps to reproduce:
- Create a bucket inside Google Cloud Storage
- Start the sorry-cypress instance using docker compose

```
version: '3.6'

services:

  mongo:
    image: mongo:4.2
    volumes:
      - ./data/data-mongo-cypress:/data/db

  redis:
    image: redis:alpine

  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      DASHBOARD_URL: http://localhost:8080
      EXECUTION_DRIVER: '../execution/mongo/driver'
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      SCREENSHOTS_DRIVER: '../screenshots/minio.driver'
      MINIO_ACCESS_KEY: 'root'
      MINIO_SECRET_KEY: 'password'
      MINIO_ENDPOINT: 'storage'
      MINIO_URL: 'http://localhost'
      MINIO_PORT: '9000'
      MINIO_USESSL: 'false'
      MINIO_BUCKET: cypress-bucket
      REDIS_URI: 'redis://redis:6379'
    ports:
      - 1234:1234
    depends_on:
      - storage
      - mongo
      - redis

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
    ports:
      - 4000:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://localhost:4000
      GRAPHQL_CLIENT_CREDENTIALS: ''
      PORT: 8080
      CI_URL: ''
    ports:
      - 8080:8080
    depends_on:
      - api
      - mongo

  storage:
    image: minio/minio
    hostname: 'storage'
    environment:
      MINIO_ACCESS_KEY: 'root'
      MINIO_SECRET_KEY: 'password'
      GOOGLE_APPLICATION_CREDENTIALS: /service-account.json
    volumes:
      - ./service-account.json:/service-account.json
    command: gateway --json gcs my-project
    ports:
      - 9000:9000
```

## Environment

- sorry-cypress version: `1.0.0-rc.10`
- cypress version: `7.3.0`
- platform: `docker`
- director: `1.0.0-rc.10`
- service: `director | dashboard`

Issue 1: The content-type for the videos and images isn't set to `video/mp4` and `image/png` respectively inside the Google Cloud Storage Bucket.

Issue 2: The images and videos are not being loaded inside the dashboard. 
I have also set CORS on the storage bucket to allow files to be loaded.

`gsutil cors set cors.json gs://cypressgci`
```
[
    {
      "origin": ["*"],
      "method": ["GET", "PUT", "POST", "DELETE", "OPTIONS"],
      "responseHeader": ["Content-Type"],
      "maxAgeSeconds": 3628800
    }
]
```

**Comment by amalhotragannett** [comment]
Issue resolved by running by the below command:

```
mc config host add gcs http://localhost:9000 user password && \
mc mb gcs/cypress-gci && \
mc policy set download gcs/cypress-gci
```

**Comment by phoenix-bjoern** [comment]
In case you use the Helm chart, you can set the policy for the bucket to "download" on the first deployment:

```
minio:
  enabled: true
  defaultBucket:
    enabled: false
    name: "sorry-cypress"
  buckets:
    - name: "sorry-cypress"
      policy: download
      versioning: false
```

To protect the downloads you could set some IP whitelisting or BasicAuth to the minio ingress:

```
minio:
  ...
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/whitelist-source-range: <you ip list>
```
