### ISSUE TITLE
Director service skips one spec file

### ISSUE THREAD

**Issue by romankhomitskyi** [sorry-cypress/sorry-cypress#543]
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [ ] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary
First I change url using patch function then  I run my tests using the following command
```
 yarn cypress run --browser chrome --parallel --record --key somekey1 --ci-build-id n8
```
Even though I passing different `--ci-build-id`, I see that run does not include one spec(see screenshots), I guess it randomly skips one spec file

My set up only includes director service

```
cypress-director:
    image: agoldis/sorry-cypress-director:latest
    container_name: "cypress-director"
    environment:
      DASHBOARD_URL: http://localhost:8080
      SCREENSHOTS_DRIVER: ../screenshots/dummy.driver
    networks:
      - home
```
I have tried to restart & rebuild director service, I have killed all containers

## How to reproduce

1. Use only director service and  run `yarn cypress run --browser chrome --parallel --record --key somekey1 --ci-build-id n8`

## Relevant logs / screenshots

![image](https://user-images.githubusercontent.com/57874507/155998827-2943b9df-ddc9-468a-ac53-ceac11b5ac9e.png)

## Environment

- sorry-cypress version: `<2.1.1>`
- cypress version: `<9.5.0>`
- platform: `docker`
- service: `director`
