### ISSUE TITLE
Dashboard cannot contact GRAPHQL_SCHEMA_URL when set to something other than http://localhost:4000

### ISSUE THREAD

**Issue by Liam-Deacon** [sorry-cypress/sorry-cypress#549]
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found no answer to my problem
- [ ] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [ ] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

I am unable to create new projects or contact the `api` service from the `dashboard` service via `http://localhost:8080` when using a modified sorry-cypress stack based off `docker-compose.minio.yml` that sandboxes all services into their own network (with the exception of `dashboard` and `api` services, which are bridged to docker localhost).

This is likely due to the fact that it looks like the `dashboard` service is a statically bundled web app served via nginx and not a live node server capable of resolving the hosts accessible from dashboard container itself. As such this may not really be a bug so much as potentially a case for an alternative image to handle some test setups.

## How to reproduce

Running `docker-compose --profile=e2e-testing up -d` with a modified `docker-compose.yml` succesfully starts all services (and the createbuckets job), however when navigating to `http://localhost:8080` (a.k.a. the dashboard) I cannot fetch any data from the `api` service[1].

It looks like this may be due to the fact that the `api` service is not in my host's DNS records. Performing a `docker-compose --profile=e2e-testing exec dashboard` and then doing a ping to the `api` service works[2].

```yaml
# docker-compose.yml
version: '3.8'

networks:
  docker-host-network:
    driver: bridge
  e2e-testing-network:
    internal: true
    ipam:
      driver: default
    name: e2e-testing-network

services:
  mongo:
    image: mongo:4.2
    container_name: sorry-cypress-mongo
    hostname: mongo
    volumes:
      - e2e-testing-cypress-mongo-data:/data/db
    networks:
      e2e-testing-network:
        aliases:
          - mongo
          - mongo.sorrycypress.e2e.testing
    ports:
      - 27017:27017
    profiles:
      - e2e-testing

  director:
    image: agoldis/sorry-cypress-director:latest
    container_name: e2e-testing-cypress-director
    hostname: director
    environment:
      DASHBOARD_URL: http://dashboard.sorrycypress.e2e.testing:8080
      EXECUTION_DRIVER: '../execution/mongo/driver'
      MONGODB_URI: 'mongodb://mongo.sorrycypress.e2e.testing:27017'
      MONGODB_DATABASE: 'sorry-cypress'

      SCREENSHOTS_DRIVER: '../screenshots/minio.driver'
      MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
      MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
      MINIO_ENDPOINT: 'storage'
      MINIO_URL: 'http://storage.sorrycypress.e2e.testing'
      MINIO_PORT: '9000'
      MINIO_USESSL: 'false'
      MINIO_BUCKET: sorry-cypress
    networks:
      e2e-testing-network:
        aliases:
          - director
          - director.sorrycypress.e2e.testing
    depends_on:
      - mongo
      - storage
    profiles:
      - e2e-testing

  api:
    image: agoldis/sorry-cypress-api:latest
    container_name: sorry-cypress-api
    hostname: api
    environment:
      MONGODB_URI: 'mongodb://mongo.sorrycypress.e2e.testing:27017'
      MONGODB_DATABASE: 'sorry-cypress'
    ports:
      - 4000:4000
    networks:
      e2e-testing-network:
        aliases:
          - api.sorrycypress.e2e.testing
      docker-host-network:
    depends_on:
      - mongo
    profiles:
      - e2e-testing

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    container_name: sorry-cypress-dashboard
    hostname: dashboard
    domainname: sorrycypress.e2e.testing
    environment:
      GRAPHQL_SCHEMA_URL: http://api.sorrycypress.e2e.testing  # http://localhost:4000 works
      GRAPHQL_CLIENT_CREDENTIALS: ''
      PORT: '8080'
      CI_URL: ''
    ports:
      - 8480:8480
    networks:
      e2e-testing-network:
        aliases:
          - dashboard
          - dashboard.sorrycypress.e2e.testing
      docker-host-network:
    depends_on:
      - mongo
      - api
    profiles:
      - e2e-testing

  storage:
    image: minio/minio
    hostname: storage
    environment:
      MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
      MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
    volumes:
      - minio-data:/data
    command: server /data
    networks:
      e2e-testing-network:
        aliases:
          - storage.sorrycypress.e2e.testing
    profiles:
      - e2e-testing

  createproject:
    image: alpine/curl
    depends_on:
      - e2e-testing-cypress-api
    entrypoint: >
      curl --fail -X POST -H "Content-Type: application/json" -d \'{"operationName":"createProject","variables":{"project":{"projectId":"MyProject","inactivityTimeoutSeconds":600,"projectColor":"#03a9f4"}},"query":"mutation createProject($$project: CreateProjectInput!) {\n  createProject(project: $$project) {\n    projectId\n    inactivityTimeoutSeconds\n    projectColor\n    __typename\n  }\n}\n"}\' api.sorrycypress.e2e.testing:4000
    networks:
      e2e-testing-network:
    profiles:
      - e2e-testing

  createbuckets:
    image: minio/mc
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc config host add myminio http://storage.sorrycypress.e2e.testing:9000 MW32h3gd6HvjBEgTRx t6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7;
      /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress;
      /usr/bin/mc mb myminio/sorry-cypress;
      /usr/bin/mc policy set download myminio/sorry-cypress;
      /usr/bin/mc policy set public myminio/sorry-cypress;
      exit 0;
      "
    networks:
      e2e-testing-network:
    profiles:
      - e2e-testing

volumes:
  mongo-data:
  minio-data:
```

## Relevant logs / screenshots

[1] ![image](https://user-images.githubusercontent.com/3184694/157556477-30040a41-72f1-482d-b2c1-c6368b3e7ee6.png)
[2] ![image](https://user-images.githubusercontent.com/3184694/157557395-64cb5b37-a638-4548-8f8e-cc3cbe9c4b0b.png)

## Environment

- sorry-cypress version: `v2.1.1`
- cypress version: `n/a`
- platform: `docker`
- service: `api & dashboard`
