### ISSUE TITLE
Sorry-cypress images in error 403 because my screenshoots are saved as folders in minio

### ISSUE THREAD

**Issue by jeremy-rafflin** [sorry-cypress/sorry-cypress#674]
Hi, I have install sorry-cypress by using docker-compose.minio.yml , it's work well, but screenshoots in sorry-cypress are in error 403.

When go to image url, i see : 

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied.</Message>
<Key>b2bc7cfae5cf96331ad54e876569c58d.png</Key>
<BucketName>sorry-cypress</BucketName>
<Resource>
/sorry-cypress/b2bc7cfae5cf96331ad54e876569c58d.png
</Resource>
<RequestId>1721E0CF2A7E2566</RequestId>
<HostId>bd76d676-3156-4308-994a-331f31c11f88</HostId>
</Error>
```

## How to reproduce
I use docker-compose.minio.yml file from this repository.
I have juste change all occurence of 'localhost' to my IP.

## Relevant logs / screenshots
In my volume, screenshots are stored as folders that contain au xl.meta file

![sorry_cypress](https://user-images.githubusercontent.com/5859762/198238628-8d42dfff-9572-4176-95d6-24bf8fa742ad.PNG)
![sorry-cypress-meta](https://user-images.githubusercontent.com/5859762/198239702-23a7ddcd-407b-4495-a3cf-d4ae3a3bb87f.PNG)

## Environment

My docker-compose file : 

```
version: '3.6'

services:
  mongo:
    image: mongo:4.4
    volumes:
      - ./data/data-mongo-cypress:/data/db
    ports:
      - 27017:27017
  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      DASHBOARD_URL: http://172.22.246.6:8080
      EXECUTION_DRIVER: '../execution/mongo/driver'
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'

      SCREENSHOTS_DRIVER: '../screenshots/minio.driver'
      GITLAB_JOB_RETRIES: 'false'
      MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
      MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
      MINIO_ENDPOINT: '172.22.246.6'
      MINIO_URL: 'http://172.22.246.6'
      MINIO_PORT: '9000'
      MINIO_USESSL: 'false'
      MINIO_BUCKET: sorry-cypress

    ports:
      - 1234:1234
      - 9000:9000
    depends_on:
      - mongo

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      APOLLO_PLAYGROUND: 'false'
    ports:
      - 4000:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://172.22.246.6:4000
      GRAPHQL_CLIENT_CREDENTIALS: ''
      PORT: 8080
      CI_URL: ''
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - api

  storage:
    image: minio/minio
    network_mode: service:director
    environment:
      MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
      MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
    volumes:
      - ./data/data-minio-cypress:/data
    command: server /data

  createbuckets:
    image: minio/mc
    network_mode: service:director
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc config host add myminio http://172.22.246.6:9000 MW32h3gd6HvjBEgTRx t6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7;
      /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress;
      /usr/bin/mc mb myminio/sorry-cypress;
      /usr/bin/mc policy set download myminio/sorry-cypress;
      /usr/bin/mc policy set public myminio/sorry-cypress;
      exit 0;
      "
```
