### ISSUE TITLE
Getting 403 forbidden trying to access screenshots and videos on docker container

### ISSUE THREAD

**Issue by dusloth** [sorry-cypress/sorry-cypress#677]
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [x] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

Following this guide (https://docs.sorry-cypress.dev/guide/dashboard-and-api) while all test text results are showing properly, screenshots and video say 403 forbidden error

I have tried changing ports to no avail.

Example URL: http://localhost:9000/sorry-cypress/11d46b19e7a7970498a6033772612b51.png

Output:
`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied.</Message>
<Key>11d46b19e7a7970498a6033772612b51.png</Key>
<BucketName>sorry-cypress</BucketName>
<Resource>/sorry-cypress/11d46b19e7a7970498a6033772612b51.png</Resource>
<RequestId>172580916BFCF850</RequestId>
<HostId>600b1a9f-48a3-45c7-9d49-00b5fc0a8327</HostId>
</Error>`

## How to reproduce

1. Running 'docker-compose -f ./docker-compose.minio.yml up' with the following docker-compose.minio file

```
version: '3.6'

services:
  mongo:
    image: mongo:4.4
    volumes:
      - ./data/data-mongo-cypress:/data/db
    ports:
      - 27017:27017
  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      DASHBOARD_URL: http://localhost:8080
      EXECUTION_DRIVER: '../execution/mongo/driver'
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'

      SCREENSHOTS_DRIVER: '../screenshots/minio.driver'
      GITLAB_JOB_RETRIES: 'false'
      MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
      MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
      MINIO_ENDPOINT: 'localhost'
      MINIO_URL: 'http://localhost'
      MINIO_PORT: '9000'
      MINIO_USESSL: 'false'
      MINIO_BUCKET: sorry-cypress
      PROBE_LOGGER: "false"
    ports:
      - 1234:1234
      - 9000:9000
    depends_on:
      - mongo

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      APOLLO_PLAYGROUND: 'false'
    ports:
      - 4000:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://localhost:4000
      GRAPHQL_CLIENT_CREDENTIALS: ''
      PORT: 8080
      CI_URL: ''
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - api

  storage:
    image: minio/minio
    network_mode: service:director
    environment:
      MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
      MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
    volumes:
      - ./data/data-minio-cypress:/data
    command: server /data

  createbuckets:
    image: minio/mc
    network_mode: service:director
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc config host add myminio http://localhost:9000 MW32h3gd6HvjBEgTRx t6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7;
      /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress;
      /usr/bin/mc mb myminio/sorry-cypress;
      /usr/bin/mc policy set download myminio/sorry-cypress;
      /usr/bin/mc policy set public myminio/sorry-cypress;
      exit 0;
      "
```

## Relevant logs / screenshots

No logs showing in console. The dashboard will not show videos or screenshots 403 forbidden error

![image](https://user-images.githubusercontent.com/16986825/200474961-b979f7c3-09a5-4294-ba6e-4f8020842931.png)

## Environment

- sorry-cypress version: `latest`
- cypress version: `latest`
- platform: `docker`
- service: `director`
- OS: Windows 10 with Cygwin
