### ISSUE TITLE
No screenshot recorded

### ISSUE THREAD

**Issue by andisan86** [sorry-cypress/sorry-cypress#713]
Please note - issues that are not following the template will be closed automatically:

- [:heavy_check_mark:] I have verified that all sorry-cypress services are running and accessible
- [:heavy_check_mark:] I have read documentation and found no answer to my problem
- [:heavy_check_mark:] I have searched issues / discussions and found to answer to my problem
- [:heavy_check_mark:] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [:heavy_check_mark:] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

No screenshot recorded in my test run. I can confirm that `sorry-cypress` bucket was created in minio with permission `public`.

## Relevant logs / screenshots
![image](https://user-images.githubusercontent.com/24508969/209946005-d04db576-ed03-4c2e-bd49-6649c53adfc7.png)

Here is my yml:
```
version: '3.6'

services:
  mongo:
    image: mongo:4.4
    volumes:
      - ./data/data-mongo-cypress:/data/db
    ports:
      - 27017:27017
  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      DASHBOARD_URL: http://18.138.145.129:8080
      EXECUTION_DRIVER: '../execution/mongo/driver'
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'

      SCREENSHOTS_DRIVER: '../screenshots/minio.driver'
      GITLAB_JOB_RETRIES: 'false'
      MINIO_ROOT_USER: 'MW32h3gd6HvjBEgTRx'
      MINIO_ROOT_PASSWORD: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
      MINIO_ENDPOINT: '18.138.145.129'
      MINIO_URL: 'http://18.138.145.129'
      MINIO_PORT: '9000'
      MINIO_USESSL: 'false'
      MINIO_BUCKET: sorry-cypress

    ports:
      - 1234:1234
      - 9000:9000
      - 9001:9001
    depends_on:
      - mongo

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      APOLLO_PLAYGROUND: 'false'
    ports:
      - 4000:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://18.138.145.129:4000
      GRAPHQL_CLIENT_CREDENTIALS: ''
      PORT: 8080
      CI_URL: ''
    ports:
      - 8085:8080
    depends_on:
      - mongo
      - api

  storage:
    image: minio/minio
    network_mode: service:director
    environment:
      MINIO_ROOT_USER: 'MW32h3gd6HvjBEgTRx'
      MINIO_ROOT_PASSWORD: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
    volumes:
      - ./data/data-minio-cypress:/data
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    network_mode: service:director
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc config host add myminio http://18.138.145.129:9000 MW32h3gd6HvjBEgTRx t6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7;
      /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress;
      /usr/bin/mc mb myminio/sorry-cypress;
      /usr/bin/mc anonymous set download myminio/sorry-cypress;
      /usr/bin/mc anonymous set public myminio/sorry-cypress;
      exit 0;
      "
```

## Environment

- sorry-cypress version: `2.5.1`
- platform: `docker | aws`
- service: `dashboard | director`
