### ISSUE TITLE
Minio screenshots not rendered from sorry-cypress dashboard

### ISSUE THREAD

**Issue by jwohlfahrt** [sorry-cypress/sorry-cypress#732]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `2.4.2`
  - cypress version: `12.3.0`
  - cy2 version: `4.0.5`
  - platform: `k8s`
  - service: `all`
```

</details>

### Describe the bug

Minio screenshots do not load directly in the sorry-cypress dashboard, and can only be downloaded from object urls in minio instance browser interface itself. We have deployed sorry-cypress via k8s using the available charts linked to in docs. Minio is set as the screenshot driver, and default bucket was created with a policy of `download`.

From looking at [stack overflow](https://stackoverflow.com/questions/63700504/minio-render-images-in-browser), it looks like images might need to be uploaded with an image content-type, but I don't see that in the code explicitly. Not sure if that matters or not, but figured I'd include.

### Expected behavior

Minio screenshots should load directly in the sorry-cypress dashboard.

### Reproduction steps

I don't have any clear repro steps, but can share some minio configurations in our chart:
```
minio:
      defaultBucket:
        policy: download
      enabled: true
      endpoint: sorry-cypress-minio.platform.svc.cluster.local
      readUrlPrefix: https://sorry-cypress.eng.theknotww.com/minio/sorry-cypress
      url: https://sorry-cypress.eng.theknotww.com/minio
```

### Full log and debug output

<details>

```
// Put your logs below this line

N/a
```

</details>
