### ISSUE TITLE
failed to upload artifact 

### ISSUE THREAD

**Issue by drewklein20** [sorry-cypress/sorry-cypress#749]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>
```
  - sorry-cypress version: `3.6`
  - cypress version: `12.6.0`
  - cy2 version: `4.0.6`
  - platform: `docker`
  - service: `all`
```

docker-compose.minio.yml
```
version: '3.6'

# Replace each testUser with the desired username
# Replace each testing123 with the desired password
# Replace each localhost with the publicly available ip address or url without http(s)
# Replace localhost with the publicly available ip address or url without http(s)

services:
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'testUser'
      MONGO_INITDB_ROOT_PASSWORD: 'testing123'
    volumes:
      - ./data/data-mongo-cypress:/data/db
    ports:
      - 27017:27017
  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      DASHBOARD_URL: http://localhost:8080
      EXECUTION_DRIVER: '../execution/mongo/driver'
      MONGODB_URI: 'mongodb://testUser:testing123@mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'

      SCREENSHOTS_DRIVER: '../screenshots/minio.driver'
      GITLAB_JOB_RETRIES: 'false'
      MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
      MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
      MINIO_ENDPOINT: 'localhost'
      MINIO_URL: 'http://localhost'
      MINIO_PORT: '9000'
      MINIO_USESSL: 'false'
      MINIO_BUCKET: sorry-cypress
      PROBE_LOGGER: "false"
    ports:
      - 1234:1234
      - 9000:9000
      - 9090:9090
    depends_on:
      - mongo

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: 'mongodb://testUser:testing123@mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      APOLLO_PLAYGROUND: 'false'
    ports:
      - 4000:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://localhost:4000
      GRAPHQL_CLIENT_CREDENTIALS: ''
      PORT: 8080
      CI_URL: ''
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - api

  storage:
    image: minio/minio
    network_mode: service:director
    environment:
      MINIO_ROOT_USER: 'drew'
      MINIO_ROOT_PASSWORD: 'helloworlddrew'
    volumes:
      - ./data/data-minio-cypress:/data
    command: minio server --console-address ":9090" /data

  createbuckets:
    image: minio/mc
    network_mode: service:director
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc config host add myminio http://localhost:9000 drew helloworlddrew;
      /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress;
      /usr/bin/mc mb myminio/sorry-cypress;
      /usr/bin/mc anonymous set download myminio/sorry-cypress;
      /usr/bin/mc anonymous set public myminio/sorry-cypress;
      exit 0;
      "

```
</details>

### Describe the bug

I'm noticing cypress screenshots are failing to make it to the minio bucket. I followed the latest instructions for the sorry-cypress kit. When a test fails, I see a "failed to upload artifact" error when using _DEBUG=cypress:server:*_. Any ideas on how to debug this further? I've verified I can login to the minio console and files can be uploaded manually to the bucket.

### Expected behavior

Screenshot of failed tests should successfully be uploaded to minio bucket

### Reproduction steps

1.  Create docker container using supplied docker-compose.
2.  Write a tests that will fail.
3.  Observe if failed test screenshot is uploaded to minio.

### Full log and debug output

<details>

```
// Put your logs below this line
cypress:server:cloud:api response { screenshotUploadUrls: [ { readUrl: 'http://localhost:9000/sorry-cypress/9115a9994eab46b21a16e02a74ff10f3.png', uploadUrl: 'http://localhost:9000/sorry-cypress/9115a9994eab46b21a16e02a74ff10f3.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=MW32h3gd6HvjBEgTRx%2F20230223%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230223T014202Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=1fd4e2b479be8bab0dd15ce2b4d3402ee735c925cb202283332f588f85a3a9d6', screenshotId: 'ny9rg' } ] } +77ms
  cypress:server:record failed to upload artifact { file: 'tests/e2e/screenshots/broken.cy.js/Toolbar Tests -- supports docking and undocking the nav drawer by clicking on the hamburger menu (failed).png', stack: 'RequestError: Error: read ECONNRESET\n' + '    at new r (<embedded>:1737:501415)\n' + '    at ee.callback (<embedded>:1737:507416)\n' + '    at e.callback.s.callback [as _callback] (<embedded>:1737:506862)\n' + '    at s._callback.s.callback.s.callback (<embedded>:1955:65115)\n' + '    at ee.emit (node:events:527:28)\n' + '    at ee.onRequestError (<embedded>:1955:74057)\n' + '    at ClientRequest.emit (node:events:527:28)\n' + '    at Socket.socketErrorListener (node:_http_client:454:9)\n' + '    at Socket.emit (node:events:527:28)\n' + '    at emitErrorNT (node:internal/streams/destroy:157:8)\n' + '    at emitErrorCloseNT (node:internal/streams/destroy:122:3  - Failed Uploading (1/1) tests/e2e/screenshots/broken.cy.js/Toolbar Tests -- supports docking and undocking the nav drawer by clicking on the hamburger menu (failed).png
)\n' + '    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)' } +86ms

```

</details>
