### ISSUE TITLE
X-Amz-Expires=NaN. Still reproducing #797

### ISSUE THREAD

**Issue by n0m44** [sorry-cypress/sorry-cypress#808]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - cypress-cloud version: 1.7.4
  - cypress version: 10.11 | 12.16
  - platform: docker compose
  - service: director

```

</details>

### Describe the bug

Still reproducing #797

Copied:
```
Cypress cannot upload artifacts to minio, no errors in logs, 15 June it worked with tags latest, but 16 June, when I deployed it to another environment it already broken
reason: director is generating uploadUrl with X-Amz-Expires=NaN

when I called upload with curl inside container, I saw reason:
curl "http://storage:9000/sorry-cypress/e68efbf1-5a74-44f0-ba60-55403c01da2d.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXX%2F20230620%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230620T082334Z&X-Amz-Expires=NaN&X-Amz-SignedHeaders=host&X-Amz-Signature=EXAMPLE"

<?xml version="1.0" encoding="UTF-8"?> <Error><Code>AuthorizationQueryParametersError</Code><Message>X-Amz-Expires should be a number</Message><Key>e68efbf1-5a74-44f0-ba60-55403c01da2d.mp4</Key><BucketName>sorry-cypress</BucketName><Resource>/sorry-cypress/e68efbf1-5a74-44f0-ba60-55403c01da2d.mp4</Resource><RequestId>176A5B419C3D6F47</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error> 

fix: I change director's image tag to agoldis/sorry-cypress-director:2.5.4
and it started work
```
that really helpfull: `fix: I change director's image tag to agoldis/sorry-cypress-director:2.5.4`

### Expected behavior

X-Amz-Expires must be the UPLOAD_EXPIRY_SECONDS from env or default value

### Reproduction steps

my yml file:
```
version: '3.6'

# Replace each <mongo-user> with the desired username
# Replace each <mongo-pass> with the desired password
# Replace each <minio-ip-address> with the publicly available ip address or url without http(s)
# Replace <graphql-ip-address> with the publicly available ip address or url without http(s)

services:
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'mongo'
      MONGO_INITDB_ROOT_PASSWORD: 'mongo'
    volumes:
      - ./data/data-mongo-cypress:/data/db
    ports:
      - 27017:27017
  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      DASHBOARD_URL: http://localhost:9898
      EXECUTION_DRIVER: '../execution/mongo/driver'
      MONGODB_URI: 'mongodb://mongo:mongo@mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      SCREENSHOTS_DRIVER: '../screenshots/minio.driver'
      GITLAB_JOB_RETRIES: 'false'
      MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
      MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
      MINIO_ENDPOINT: '127.0.0.1'
      MINIO_URL: 'http://127.0.0.1'
      MINIO_PORT: '9000'
      MINIO_USESSL: 'false'
      MINIO_BUCKET: sorry-cypress
      PROBE_LOGGER: "false"
    ports:
      - 1234:1234
      - 9000:9000
      - 9090:9090
    depends_on:
      - mongo

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: 'mongodb://mongo:mongo@mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      APOLLO_PLAYGROUND: 'false'
    ports:
      - 4000:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://localhost:4000
      GRAPHQL_CLIENT_CREDENTIALS: ''
      PORT: 9898
      CI_URL: ''
    ports:
      - 9898:9898
    depends_on:
      - mongo
      - api

  storage:
    image: minio/minio
    network_mode: service:director
    environment:
      MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
      MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
    volumes:
      - ./data/data-minio-cypress:/data
    command: minio server --console-address ":9090" /data

  createbuckets:
    image: minio/mc
    network_mode: service:director
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc config host add myminio http://localhost:9000 MW32h3gd6HvjBEgTRx t6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7;
      /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress;
      /usr/bin/mc mb myminio/sorry-cypress;
      /usr/bin/mc anonymous set download myminio/sorry-cypress;
      /usr/bin/mc anonymous set public myminio/sorry-cypress;
      exit 0;
      "
```
 + i was try add to director's env:
UPLOAD_EXPIRY_SECONDS: 180
UPLOAD_EXPIRY_SECONDS: '180'

still NaN when it try parsing

I tried running it (only director serivce) locally on master and everything worked ok, including the UPLOAD_EXPIRY_SECONDS variable.

Maybe image is not updated in docker?

### Full log and debug output

<details>

```json
{
  "level":30,
  "time":1688224815962,
  "requestId":"df91148f-df2c-4b2e-bece-787ba43c65ec",
  "instanceId":"723d8aed-35e6-47b0-af40-dd2db159eacd",
  "screenshotUploadUrls":[],
  "videoUploadInstructions":{
    "readUrl":"http://127.0.0.1:9000/sorry-cypress/723d8aed-35e6-47b0-af40-dd2db159eacd.mp4",
    "uploadUrl":"http://127.0.0.1:9000/sorry-cypress/723d8aed-35e6-47b0-af40-dd2db159eacd.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=MW32h3gd6HvjBEgTRx%2F20230701%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230701T152015Z&X-Amz-Expires=NaN&X-Amz-SignedHeaders=host&X-Amz-Signature=a956f7eda096acce1bb23d999b7b421ff00fb1a8f24e03b2d2fbb2f9a62465e9"
  },
  "msg":"Sending assets upload URLs"
}
```

</details>
