### ISSUE TITLE
 MongoError: Authentication failed.

### ISSUE THREAD

**Issue by patricklongo1** [sorry-cypress/sorry-cypress#865]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `latest`
  - cypress version: `13.3.0`
  - cy2 version: `not sure`
  - platform: `docker`
  - service: `mongo`

```

</details>

### Describe the bug

Im trying to run the docker-compose.minio.yml, but im facing some mongo error.

my docker-compose.minio.yml,:

```
version: '3.6'
# Replace each admin with the desired username
# Replace each mongoroot123 with the desired password
# Replace each <minio-ip-address> with the publicly available ip address or url without http(s)
# Replace <graphql-ip-address> with the publicly available ip address or url without http(s)

services:
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'mongoroot123'
    volumes:
      - ./data/data-mongo-cypress:/data/db
    ports:
      - 27017:27017
  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      DASHBOARD_URL: http://localhost:8080
      EXECUTION_DRIVER: '../execution/mongo/driver'
      MONGODB_URI: 'mongodb://admin:mongoroot123@mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'

      SCREENSHOTS_DRIVER: '../screenshots/minio.driver'
      GITLAB_JOB_RETRIES: 'false'
      MINIO_ACCESS_KEY: 'minioadmin'
      MINIO_SECRET_KEY: 'minioroot123'
      MINIO_ENDPOINT: 'localhost'
      MINIO_URL: 'http://localhost'
      MINIO_PORT: '9000'
      MINIO_USESSL: 'false'
      MINIO_BUCKET: sorry-cypress
      PROBE_LOGGER: "false"
    ports:
      - 1234:1234
      - 9000:9000
      - 9090:9090
    depends_on:
      - mongo

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: 'mongodb://admin:mongoroot123@mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      APOLLO_PLAYGROUND: 'false'
    ports:
      - 4000:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://localhost:4000
      GRAPHQL_CLIENT_CREDENTIALS: ''
      PORT: 8080
      CI_URL: ''
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - api

  storage:
    image: minio/minio
    network_mode: service:director
    environment:
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'minioroot123'
    volumes:
      - ./data/data-minio-cypress:/data
    command: minio server --console-address ":9090" /data

  createbuckets:
    image: minio/mc
    network_mode: service:director
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc config host add myminio http://localhost minioadmin minioroot123;
      /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress;
      /usr/bin/mc mb myminio/sorry-cypress;
      /usr/bin/mc anonymous set download myminio/sorry-cypress;
      /usr/bin/mc anonymous set public myminio/sorry-cypress;
      exit 0;
      "
```

### Expected behavior

Run sorry cypress kit locally

### Reproduction steps

I just need some working config example for docker-compose.minio.yml

### Full log and debug output

<details>

```
// Put your logs below this line

{"t":{"$date":"2023-10-05T01:55:41.748+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"192.168.0.4:47906","connectionId":147,"connectionCount":1}}
next13-mui-cy-jest-storybook-mongo-1          | {"t":{"$date":"2023-10-05T01:55:41.754+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn147","msg":"client metadata","attr":{"remote":"192.168.0.4:47906","client":"conn147","doc":{"driver":{"name":"nodejs","version":"3.6.10"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.90.1-microsoft-standard-WSL2"},"platform":"'Node.js v16.20.2, LE (unified)"}}}
next13-mui-cy-jest-storybook-mongo-1          | {"t":{"$date":"2023-10-05T01:55:41.759+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"192.168.0.4:47920","connectionId":148,"connectionCount":2}}
next13-mui-cy-jest-storybook-mongo-1          | {"t":{"$date":"2023-10-05T01:55:41.762+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn148","msg":"client metadata","attr":{"remote":"192.168.0.4:47920","client":"conn148","doc":{"driver":{"name":"nodejs","version":"3.6.10"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.90.1-microsoft-standard-WSL2"},"platform":"'Node.js v16.20.2, LE (unified)"}}}
next13-mui-cy-jest-storybook-mongo-1          | {"t":{"$date":"2023-10-05T01:55:41.762+00:00"},"s":"I",  "c":"ACCESS",   "id":20251,   "ctx":"conn148","msg":"Supported SASL mechanisms requested for unknown user","attr":{"user":"admin@admin"}}
next13-mui-cy-jest-storybook-mongo-1          | {"t":{"$date":"2023-10-05T01:55:41.762+00:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn148","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-256","speculative":true,"principalName":"admin","authenticationDatabase":"admin","remote":"192.168.0.4:47920","extraInfo":{},"error":"UserNotFound: Could not find user \"admin\" for db \"admin\""}}
next13-mui-cy-jest-storybook-mongo-1          | {"t":{"$date":"2023-10-05T01:55:41.764+00:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn148","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-1","speculative":false,"principalName":"admin","authenticationDatabase":"admin","remote":"192.168.0.4:47920","extraInfo":{},"error":"UserNotFound: Could not find user \"admin\" for db \"admin\""}}
next13-mui-cy-jest-storybook-mongo-1          | {"t":{"$date":"2023-10-05T01:55:41.767+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn147","msg":"Connection ended","attr":{"remote":"192.168.0.4:47906","connectionId":147,"connectionCount":1}}
next13-mui-cy-jest-storybook-director-1       | MongoError: Authentication failed.
next13-mui-cy-jest-storybook-director-1       |     at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:272:20)
next13-mui-cy-jest-storybook-director-1       |     at MessageStream.emit (node:events:513:28)
next13-mui-cy-jest-storybook-director-1       |     at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
next13-mui-cy-jest-storybook-director-1       |     at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
next13-mui-cy-jest-storybook-director-1       |     at writeOrBuffer (node:internal/streams/writable:391:12)
next13-mui-cy-jest-storybook-director-1       |     at _write (node:internal/streams/writable:332:10)
next13-mui-cy-jest-storybook-director-1       |     at MessageStream.Writable.write (node:internal/streams/writable:336:10)
next13-mui-cy-jest-storybook-director-1       |     at Socket.ondata (node:internal/streams/readable:754:22)
next13-mui-cy-jest-storybook-director-1       |     at Socket.emit (node:events:513:28)
next13-mui-cy-jest-storybook-director-1       |     at addChunk (node:internal/streams/readable:315:12) {
next13-mui-cy-jest-storybook-director-1       |   ok: 0,
next13-mui-cy-jest-storybook-director-1       |   code: 18,
next13-mui-cy-jest-storybook-director-1       |   codeName: 'AuthenticationFailed'
next13-mui-cy-jest-storybook-director-1       | }
next13-mui-cy-jest-storybook-mongo-1          | {"t":{"$date":"2023-10-05T01:55:41.777+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn148","msg":"Connection ended","attr":{"remote":"192.168.0.4:47920","connectionId":148,"connectionCount":0}}
next13-mui-cy-jest-storybook-director-1       | 2023-10-05T01:55:41: PM2 log: App [dist:0] exited with code [1] via signal [SIGINT]
next13-mui-cy-jest-storybook-director-1       | 2023-10-05T01:55:41: PM2 log: App [dist:0] starting in -fork mode-
next13-mui-cy-jest-storybook-director-1       | 2023-10-05T01:55:41: PM2 log: App [dist:0] online

```

</details>
