### ISSUE TITLE
Director is not finding the mongo driver

### ISSUE THREAD

**Issue by lucasquin** [sorry-cypress/sorry-cypress#948]
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [x] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `latest`
  - cypress version: `latest`
  - cy2 version: `<here>`
  - platform: `docker`
  - service: `director`
```
</details>

### Describe the bug

Director is not finding the mongo driver.

My docker compose:
```yml
services:
  mongo:
    image: mongo:4.4
    command: mongod --port 27018 --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=sorry-cypress
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27018"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27018/test --quiet
      retries: 3

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27018/sorry-cypress?authSource=admin
      - MONGODB_DATABASE=sorry-cypress
    ports:
      - "1234:1234"

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      - GRAPHQL_SCHEMA_URL=http://api:1234
      - PORT=8080
      - CI_URL=""
    depends_on:
      - api
    ports:
      - "8080:8080"

  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      - DASHBOARD_URL=http://dashboard:8080
      - EXECUTION_DRIVER="../execution/mongo/driver"
      - MONGODB_URI=mongodb://root:password@mongo:27018/sorry-cypress?authSource=admin
      - MONGODB_DATABASE=sorry-cypress
      - SCREENSHOTS_DRIVER="../screenshots/dummy.driver"
    depends_on:
      - mongo
      - dashboard
    ports:
      - "1235:1235"

volumes:
  mongo_data:

```
Log:
```
director-1   | {"level":50,"time":1749500427487,"code":"MODULE_NOT_FOUND","requireStack":["/app/packages/director/dist/drivers/index.js","/app/packages/director/dist/lib/hooks/init.js","/app/packages/director/dist/index.js"],"stack":"Error: Cannot find module '\"../execution/mongo/driver\"'\nRequire stack:\n- /app/packages/director/dist/drivers/index.js\n- /app/packages/director/dist/lib/hooks/init.js\n- /app/packages/director/dist/index.js\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)\n    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:61:29)\n    at require (node:internal/modules/cjs/helpers:119:18)\n    at /app/packages/director/src/drivers/index.ts:31:18\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at getExecutionDriver (/app/packages/director/src/drivers/index.ts:31:18)\n    at init (/app/packages/director/src/lib/hooks/init.ts:44:3)\n    at main (/app/packages/director/src/index.ts:11:3)","type":"Error","msg":"Cannot find module '\"../execution/mongo/driver\"'\nRequire stack:\n- /app/packages/director/dist/drivers/index.js\n- /app/packages/director/dist/lib/hooks/init.js\n- /app/packages/director/dist/index.js"}
director-1   | 2025-06-09T20:20:27: PM2 log: App [dist:0] exited with code [1] via signal [SIGINT]
```

### Expected behavior

Find the mongo driver.

### Reproduction steps

Only run `docker compose up ` in my config.

### Full log and debug output

<details>

```
// Put your logs below this line


```

</details>
